// Copyright 2015 Las Venturas Playground. All rights reserved.
// Use of this source code is governed by the MIT license, a copy of which can
// be found in the LICENSE file.

#ifndef PLAYGROUND_BINDINGS_EXCEPTION_HANDLER_H_
#define PLAYGROUND_BINDINGS_EXCEPTION_HANDLER_H_

#include <list>

#include "bindings/runtime.h"

namespace bindings {

// A scoped exception source may be used to improve the clarity of exceptions generated by code ran
// because we invoked JavaScript for some reason. The reason will be included in the output.
class ScopedExceptionSource {
 public:
  explicit ScopedExceptionSource(const std::string& source);
  ~ScopedExceptionSource();
};

// The exception handler handles exceptions that are not handled in the JavaScript code by
// outputting them to the console in a neatly formatted fashion.
class ExceptionHandler {
 public:
  explicit ExceptionHandler(Runtime::Delegate* runtime_delegate);
  ~ExceptionHandler();

  enum class MessageSource {
    kScript,
    kInvocation,
    kRejectedPromise
  };

  // Called when the v8 runtime generates a message. It may also be called manually by any code
  // that maintains a v8::TryCatch before doing an operation on the engine.
  void OnMessage(v8::Local<v8::Message> message, v8::Local<v8::Value> error, MessageSource source,
                 v8::Local<v8::Promise> promise = v8::Local<v8::Promise>());

  // Revokes queued messages for the |promise|. Needed to support async try/catch statements.
  void RevokeQueuedMessages(v8::Local<v8::Promise> promise);

  // Flushes the queued unexpected promise revocations.
  void FlushMessageQueue();

  // Called when a non-recoverable error occurs within the runtime.
  void OnFatalError(const char* location, const char* message);

 private:
  Runtime::Delegate* runtime_delegate_;

  // Structure to store queued up messages. Necessary to support async try/catch statements.
  struct QueuedMessage {
    QueuedMessage(v8::Isolate* isolate, v8::Local<v8::Message> message, v8::Local<v8::Value> error,
                  MessageSource message_source, v8::Local<v8::Promise> promise)
        : message(isolate, message), error(isolate, error), message_source(message_source),
          promise(isolate, promise) {}

    QueuedMessage() = delete;
    QueuedMessage(QueuedMessage& other) = delete;

    v8::Persistent<v8::Message> message;
    v8::Persistent<v8::Value> error;
    MessageSource message_source;

    v8::Persistent<v8::Promise> promise;
  };

  // Linked list of queued messages. Avoids needing to make copies.
  std::list<QueuedMessage> queued_messages_;
};

}  // namespace bindings

#endif  // PLAYGROUND_BINDINGS_EXCEPTION_HANDLER_H_
